---
title: "Group Project (Fast Campus)"
author: "Jiwon Kim"
date: '2018-08-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(leaflet)
library(dplyr)
library(ggplot2)
library(lubridate)
library(anytime)
library(timeDate)
library(stringr)
library(readxl)
library(funModeling)
library(tidyr)
library(data.table)
library(DT)
```

# 연구 주제 및 연구 목적 
## 서울시 공공자전거
#### Airbnb, Uber 등과 같은 공유경제모델 색깔을 띈 회사들이 많이 나와 국민들의 관심 또한 커져 범정부적 차원에서도 공공 welfare를 위한 많은 프로그램들이 나왔다. 
<br> 

# 연구 범위 설정

# 구 설정이유 

# 데이터 수집 



## 변수 설명 
```{r variables, echo = FALSE}
depvariable <- readxl::read_xlsx("Data/variables.xlsx", sheet = 1, col_names = TRUE)
datatable(depvariable,
          filter = 'top', options = list(
            pageLength = 8, autoWidth = TRUE
          ))
indvariable <- readxl::read_xlsx("Data/variables.xlsx", sheet = 2, col_names = TRUE)
datatable(indvariable,
          filter = 'top', options = list(
            pageLength = 8, autoWidth = TRUE
          ))
```

# 상관분석 

# [회귀모형]



You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

